# Generated by Django 4.1.3 on 2022-11-15 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_owner', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=80, null=True)),
                ('content', models.CharField(blank=True, max_length=400, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True, null=True)),
                ('deadline', models.DateField(null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='open', max_length=20)),
                ('user', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
