# Generated by Django 4.1.3 on 2022-11-17 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
    ]
