# Generated by Django 4.1.3 on 2022-11-17 08:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_remove_task_date_posted_remove_task_deadline'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='TaskDetails',
        ),
    ]
